version: '3'
services:
  app-php-v8:
    image: php:8.1.1-fpm
    working_dir: /var/app
    volumes:
      - .:/var/app
    ports:
      - 80:80
    command: >
         bash -c "chmod 777 /var/app/install.sh &&
         /var/app/install.sh"



